// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irpshpqlcectqdtrtwqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlycHNocHFsY2VjdHFkdHJ0d3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODQ1OTQsImV4cCI6MjA3MjY2MDU5NH0.qgwcwgZGOhf4lEbBcJu-xsbH3TvM766EEwP_anMTEQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});